# Generated by Django 4.1.7 on 2023-02-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('ML', 'Milk'), ('DL', 'Dairy'), ('IC', 'Ice Cream')], max_length=5, null=True),
        ),
    ]
